{% set name = "asdf-astropy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ce081f17f2cbcf28d7ba1362d4197772fc5cd55c15960652aebf61a712ec9e97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - asdf >=2.14.4
    - asdf-coordinates-schemas >=0.3
    - asdf-transform-schemas >=0.5
    - asdf-standard >=1.1.0
    - astropy-base >=5.2.0
    - numpy >=1.24
    - packaging >=19
    - python >=3.10

test:
  imports:
    - asdf_astropy
  commands:
    - pip check
    - pytest --pyargs asdf_astropy
  requires:
    - pytest-astropy
    - scipy

about:
  home: https://github.com/astropy/asdf-astropy
  summary: ASDF serialization support for astropy
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
    - braingram
