{% set name = "asdf-astropy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 462b674601fe2c4a2f45c92bed3e21effd0d58addc7ec4335c545118bc582eb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - asdf >=2.13
    - asdf-coordinates-schemas >=0.2
    - asdf-transform-schemas >=0.2.2
    - astropy >=5.0.4
    - importlib-resources >=3
    - numpy >=1.20
    - packaging >=16.0
    - python >=3.8

test:
  imports:
    - asdf_astropy
  commands:
    - pip check
    - pytest --pyargs asdf_astropy
  requires:
    - pytest-astropy
    - scipy

about:
  home: https://github.com/astropy/asdf-astropy
  summary: ASDF serialization support for astropy
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
    - braingram
