{% set name = "asdf-astropy" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d27c7c50b012aa5f679eac4bf891117bf1e8df7e03b7367ca3054403c3397f4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools-scm
  run:
    - asdf >=3.3.0
    - asdf-coordinates-schemas >=0.4
    - asdf-transform-schemas >=0.6
    - asdf-standard >=1.1.0
    - astropy-base >=5.3.0
    - numpy >=1.26
    - packaging >=19
    - python >=3.11

test:
  imports:
    - asdf_astropy
  commands:
    - pip check
    - pytest --pyargs asdf_astropy
  requires:
    - pytest-astropy
    - scipy

about:
  home: https://github.com/astropy/asdf-astropy
  summary: ASDF serialization support for astropy
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
    - braingram
